title: Gaganjot SHAN
#logo: /assets/img/headshot_circle.png
description: Contact Information
theme: jekyll-theme-minimal

# Optional: Uncomment the logo line if you have a logo file in the specified location
#logo: /assets/img/headshot_circle.png

# Optional: Show downloads link
#show_downloads: true

# Contact Information
location: Antibes, France  
email: gagan.shan7@gmail.com
phone: "+33766356099"
linkedin: "https://www.linkedin.com/in/gaganjotshan"
gitlab: "https://gitlab.eurecom.fr/"

# Configuring the URL of your site and its base URL
#url: "https://gaganjotshan.github.io/MyPortfolio/"
#baseurl: "/your-repository-name"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

