title: Gaganjot SHAN
#logo: /assets/img/headshot_circle.png
description: Contact Information
#theme: jekyll-theme-minimal
#show_downloads: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional social links
social_links:
  email: gagan.shan7@gmail.com
  linkedin: gaganjotshan
  gitlab: https://gitlab.eurecom.fr/
  location: Antibes, France
  phone: +33766356099



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

